### PR TITLE
Add MSVC debugger visualization file

### PR DESCRIPTION
**Pull request by cmakshin**
This pull request contains a file which can be used by the Visual Studio debugger for "pretty-printing" `tsl::sparse_*` containers.

### CODE REVIEW

**Comment by Tessil** [comment]
Hello,

I made a couple of corrections similar to the natvis of the `ordered-map` project.

I was also wondering if the visualization for `tsl::sparse_map` that shows the key in the name column was necessary? As it add extra code to maintain, what would be the advantage of having this view in addition to the first one?

**Comment by cmakshin** [comment]
Hello.

Showing the key in the name column was done for two reasons:
1) I find it more convenient for inspecting the container's contents;
2) that's how `std::map` visualizer works [by default]. `std::unordered_map` visualizer also shows the key in the name column, but, for some reason, the whole key-value pair in the value column.

**Comment by Tessil** [comment]
Effectively. 

I have to check a bit as the other `natvis` files you contributed just use a simple index (which is preferable for `tsl::ordered_map`). I have to see if I can add the key in the name of the column for the other projects in `tsl` as I would like to keep some consistency across the projects.

**Comment by Tessil** [comment]
I think it should be better to keep the (key, value) in the column index to mimic more closely what Microsoft did with `std::unordered_map`. If they change it in the future, I'll see to change it here too.

**Comment by Tessil** [comment]
I merged the changes, thank you for your contribution.

**Pull request merged**
